# Generated by the release workflow in connickshields/sightglass from
# packaging/sightglass.rb.tmpl. Edits made here are overwritten by the next
# release, so change the template instead.
cask "sightglass" do
  version "0.1.2"
  sha256 "610962eb8f30c12d93dc4e4332d3655c14d440db0653d471d63d8e97590f6190"

  url "https://github.com/connickshields/sightglass/releases/download/v#{version}/Sightglass-#{version}.zip"
  name "Sightglass"
  desc "Menu bar gauges for JSON status files from long-running jobs"
  homepage "https://github.com/connickshields/sightglass"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: :sequoia

  app "Sightglass.app"

  # Sightglass is ad-hoc signed, not notarized, so Gatekeeper refuses to open
  # a quarantined copy. Removing the attribute lets it launch.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Sightglass.app"]
  end

  uninstall quit: "io.github.connickshields.sightglass"

  zap trash: [
    "~/Library/Application Support/Sightglass",
    "~/Library/Preferences/io.github.connickshields.sightglass.plist",
  ]
end
